name: SleepyShop
version: "0.6"
main: com.jotrorox.sleepyshop.SleepyShop
api-version: "1.21"
authors: [Johannes (jotrorox) Müller <mail@jotrorox.com>]
website: https://jotrorox.com

permissions:
  sleepyshop.admin:
    description: "Allows you to access the Chests and remove shops if needed"
    default: op
